#!/bin/bash
#Script que, por medio de un menú, permitirá:
	# Visualizar el contenido del directorio home del usuario actual
	# Visualizar el espacio libre del disco
	# Si el usuario se llama Noel, mostrar mensaje "Ánimo Noel, el 25 de diciembre está al caer"
#Revisado por: Hector de la Cruz y Men-Cheung
#No ha habido errores pero si se ha mejorado la parte del $opt=Mensaje
#Se ha introducido nuevos comentarios como guia del script

# Definimos las opciones y dejamos que el usario elija la accion que quiere llevar a cabo
PS3="Elija una opción: "
OPCIONES="UsuarioActual EspacioLibre Mensaje Salir"
select opt in $OPCIONES
do
	if [[ $opt = "UsuarioActual" ]]
	then
		echo Estas en el directorio:
# pwd me muestra en que directorio se encuentra el usuario
		pwd
		echo Visualizamos su contenido:
		ls -l .

	elif [[ $opt = "EspacioLibre" ]]
	then
		echo El espacio disponible del disco es de:
# Consultamos el sistema de ficheros, definimos la cadena con la que queremos buscar la linea y elegimos los caracteres que muestran el espacio disponible
		df -h | grep "/dev/sda1" | cut -c29-35
	
	elif [[ $opt = "Mensaje" ]]
	then
		echo "¿Es el usuario Noel?"
		echo "1 si"
		echo "2 no"
		echo "Introduzca su opción:"
# Con el read se mete un valor en la variable y con el case lee la variable y si coincide con alguna de las opciones, esta se ejecuta
		read respuesta
		case $respuesta in 
			1 | si | s ) echo "Ánimo Noel, el 25 de diciembre esta al caer"
			;;
			2 | no | n ) echo "No se ha detectado coincidencia"
			;;
			*) echo "Opción incorrecta"
			;;
		esac
		

	elif [[ $opt = "Salir" ]]
	then
		echo "FIN"
		break
	else
		echo "Opción errónea."
	fi
done

