#!/bin/bash
#El script esta diseñado para que se muestren los fichero con un tamaño mayor d$

echo "Bienvenido, aqui te mostraremos los ficheros superiores a 1M"

read -p "Introduce la ruta del directorio: " ruta


if [[ -d $ruta ]];
        then
#Si el directorio existe, contabilizará los ficheros que sean superiores a ese tamaño
        fich=$(find $ruta -size +1000k -name "*.*" | wc -l)

        echo "Hay $fich fichero/s"
        else
#En caso de que el directorio no exista mostrará un mensaje de que la ruta no existe
        echo "La ruta no existe"

fi
