#!/bin/bash
#El script esta diseñado para que se muestren los fichero con un tamaño mayor d$

echo "Bienvenido, aqui te mostraremos los ficheros superiores a 1M"

read -p "Introduce la ruta del directorio: " ruta


if [[ -d $ruta ]];
        then

        fich=$(find $ruta -size +100k -name "*.*" | wc -l)

        echo "Hay $fich fichero/s"
        else

        echo "La ruta no existe"

fi
